spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-length: ${JWT_EXPIRATION_LENGTH}
  oauth:
    kakao:
      client-id: ${REST_API_KEY}
      redirect-uri: ${REDIRECT_URI}
      user-info-url: https://kapi.kakao.com/v2/user/me
      token-url: https://kauth.kakao.com/oauth/token

springdoc:
  swagger-ui:
    path: "/api-doc"