spring:
  datasource:
    url: jdbc:h2:~/covigator;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true
        default_batch_fetch_size: 10
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 10MB
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DB_DATABASE}
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-length: ${JWT_EXPIRATION_LENGTH}
  oauth:
    kakao:
      client-id: ${REST_API_KEY}
      redirect-uri: ${REDIRECT_URI}
      user-info-url: https://kapi.kakao.com/v2/user/me
      token-url: https://kauth.kakao.com/oauth/token

springdoc:
  swagger-ui:
    path: "/api-doc"

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-1
  s3:
    bucket: ${S3_BUCKET_NAME}