name: covigator-backend-ci

on:
  push: 
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

#env:
#  RESOURCE_PATH: ./src/main/resources/application.yml

env:
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_EXPIRATION_LENGTH: ${{ secrets.JWT_EXPIRATION_LENGTH }}

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Shutdown Ubuntu MySQL (SUDO)
#        run: sudo service mysql stop
#
#      - name: Connect to MySQL
#        uses: mirromutth/mysql-action@v1.1
#        with:
#          host port: 3306
#          container port: 3306
#          mysql database: 'covigator'
#          mysql user: ${{ secrets.DATABASE_USERNAME }}
#          mysql password: ${{ secrets.DATABASE_PASSWORD }}

#      - name: Set yml file
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ${{ env.RESOURCE_PATH }}
#        env:
#          spring.datasource.url: ${{ secrets.DATABASE_URL }}
#          spring.datasource.username: ${{ secrets.DATABASE_USERNAME }}
#          spring.datasource.password: ${{ secrets.DATABASE_PASSWORD }}
#          security.jwt.secret-key: ${{ secrets.JWT_SECRET_KEY }}
#          security.oauth.kakao.client-id: ${{ secrets.REST_API_KEY }}
#          security.oauth.kakao.redirect-uri: ${{ secrets.REDIRECT_URI }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info --stacktrace
